"""
app.py

Gradio app for Hugging Face Spaces.

Repo layout expected on the Space:
    app.py
    inference.py
    model_utils.py
    requirements.txt
    data/
        my_data.csv
        faiss_index.index
        product_mapping.pkl
        (all-MiniLM-L6-v2/  -- optional, cached on first run if absent)

Provides:
  - a search box UI (Gallery of product images)
  - a programmatic API endpoint (auto-generated by Gradio) returning:
        {"results": {"0": "<image_url>", "1": "<image_url>", ...}}
    callable via gradio_client, or POST to /run/predict on the Space.
"""

import gradio as gr

from inference import SemanticSearch

DATA_DIR = "data"

print("[app] loading search engine...")
engine = SemanticSearch(directory=DATA_DIR)
print("[app] ready")


def search(query: str, k: int):
    """
    Returns:
      - gallery_images: list of image URLs, for the Gradio Gallery component
      - api_response: the {"results": {...}} dict, for programmatic callers
    """
    if not query or not query.strip():
        return [], {"results": {}}

    api_response = engine.search_image_urls(query, k=int(k))
    gallery_images = list(api_response["results"].values())
    return gallery_images, api_response


with gr.Blocks(title="Semantic Product Search") as demo:
    gr.Markdown(
        "# Semantic Product Search\n"
        "Search a product catalog by meaning, not just keywords — "
        "e.g. try *\"red running shoes for men\"* or *\"formal shirt for office\"*."
    )

    with gr.Row():
        query_box = gr.Textbox(
            label="Search query",
            placeholder="e.g. red running shoes for men",
            scale=4,
        )
        k_slider = gr.Slider(
            minimum=1, maximum=20, value=10, step=1,
            label="Number of results", scale=1,
        )

    search_button = gr.Button("Search", variant="primary")

    gallery = gr.Gallery(
        label="Results",
        columns=5,
        height="auto",
        object_fit="contain",
    )

    with gr.Accordion("Raw API response", open=False):
        json_output = gr.JSON(label="results")

    search_button.click(
        fn=search,
        inputs=[query_box, k_slider],
        outputs=[gallery, json_output],
        api_name="search",
    )
    query_box.submit(
        fn=search,
        inputs=[query_box, k_slider],
        outputs=[gallery, json_output],
        api_name=False,  # avoid registering a duplicate endpoint for the same fn
    )

if __name__ == "__main__":
    demo.launch()
