"""
app.py
Gradio app for Hugging Face Spaces.
Repo layout expected on the Space:
    app.py
    inference.py
    model_utils.py
    requirements.txt
    data/
        my_data.csv
        faiss_index.index
        product_mapping.pkl
        (all-MiniLM-L6-v2/  -- optional, cached on first run if absent)
Provides:
  - a search box UI that shows the {"results": [...]} JSON of image URLs
  - a programmatic API endpoint (auto-generated by Gradio)
"""

import gradio as gr
import spaces

from inference import SemanticSearch
from sentence_transformers import SentenceTransformer

DATA_DIR = "data"

print("[app] loading search engine...")
engine = SemanticSearch(directory=DATA_DIR)
print("[app] ready")


@spaces.GPU
def _claim_gpu():
    """
    Dummy function required by ZeroGPU Spaces: at least one @spaces.GPU
    function must exist in the app or startup fails with
    'No @spaces.GPU function detected'. This is never actually called —
    all real search logic below runs on CPU as intended.
    """
    pass

@spaces.GPU
def search(query: str, k: int) -> dict:
    """Returns {"results": [...]} — same shape regardless of branch, so the
    frontend never has to special-case the response type."""
    if not query or not query.strip():
        return {"results": []}

    urls = engine.search(query, k=int(k))
    
    return {"results":urls }


with gr.Blocks(title="Semantic Product Search") as demo:
    gr.Markdown(
        "# Semantic Product Search\n"
        "Search a product catalog by meaning, not just keywords — "
        "e.g. try *\"red running shoes for men\"* or *\"formal shirt for office\"*."
    )

    with gr.Row():
        query_box = gr.Textbox(
            label="Search query",
            placeholder="e.g. red running shoes for men",
            scale=4,
        )
        k_slider = gr.Slider(
            minimum=1, maximum=20, value=10, step=1,
            label="Number of results", scale=1,
        )

    search_button = gr.Button("Search", variant="primary")

    output_box = gr.JSON(label="Results")

    search_button.click(
        fn=search,
        inputs=[query_box, k_slider],
        outputs=[output_box],
        api_name="search",
    )
    query_box.submit(
        fn=search,
        inputs=[query_box, k_slider],
        outputs=[output_box],
        api_name=False,  # avoid registering a duplicate endpoint for the same fn
    )

if __name__ == "__main__":
    # show_api=False skips generating the OpenAPI/schema docs page at launch.
    # This works around a known bug in this gradio version's gradio_client
    # schema builder (crashes on dict-typed outputs with a TypeError in
    # get_type()). The UI itself and the registered endpoints still work —
    # this only disables the auto-generated "View API" docs page.
    demo.launch(show_api=False)